apiPackage: "ru.romanow.openapi.models.client"
modelPackage: "ru.romanow.openapi.models"

debugModels: true

apiDocs: false
apiTests: false
modelDocs: false
modelTests: false

additionalProperties:
  dateLibrary: java8
  serializationLibrary: jackson

files:
  data.mustache:
    templateType: Model
    destinationFilename: .kt