apiPackage: "ru.romanow.openapi.client.client"
modelPackage: "ru.romanow.openapi.client.model"

debugModels: true
apiDocs: false
modelDocs: false
apiTests: false
modelTests: false

additionalProperties:
  dateLibrary: java8
files:
  enum_class.mustache:
    templateType: Model