apiPackage: "ru.romanow.openapi.client.rest"
modelPackage: "ru.romanow.openapi.client.models"

debugModels: true

apiDocs: false
apiTests: false
modelDocs: false
modelTests: false

additionalProperties:
  dateLibrary: java8
  serializationLibrary: jackson
  enumPropertyNaming: 'UPPERCASE'

files:
  model.mustache:
    templateType: Model
    destinationFilename: .kt