name: Destroy
on:
  workflow_dispatch:

jobs:
  plan:
    name: Destroy DigitalOcean app
    runs-on: ubuntu-latest
    environment:
      name: digitalocean
    steps:
      - uses: actions/checkout@v3

      - name: Terraform destroy
        run: |
          cd deploy/
          terraform init
          terraform destroy -auto-approve
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          TF_VAR_do_token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
          TF_VAR_docker_hub_token: ${{ secrets.DOCKER_HUB_TOKEN }}
